version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule: 
      interval: "daily"
    target-branch: "upgrade"
    # Add assignees, reviewers
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "upgrade"